// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfZIsE9b_idno3mscEFLM7KmpG50ocEV4',
    appId: '1:210878231216:web:05ea1884099f828f664175',
    messagingSenderId: '210878231216',
    projectId: 'testau-61f52',
    authDomain: 'testau-61f52.firebaseapp.com',
    storageBucket: 'testau-61f52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO1V2nPkCT51yI6TessMxXE50bsqNuigI',
    appId: '1:210878231216:android:17fc7255ee4538cc664175',
    messagingSenderId: '210878231216',
    projectId: 'testau-61f52',
    storageBucket: 'testau-61f52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAor3ldgd9pN7Rl-XCka49JtOADOQ4b8V0',
    appId: '1:210878231216:ios:da35f20e87d69cf6664175',
    messagingSenderId: '210878231216',
    projectId: 'testau-61f52',
    storageBucket: 'testau-61f52.appspot.com',
    iosBundleId: 'com.example.flutterGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAor3ldgd9pN7Rl-XCka49JtOADOQ4b8V0',
    appId: '1:210878231216:ios:da35f20e87d69cf6664175',
    messagingSenderId: '210878231216',
    projectId: 'testau-61f52',
    storageBucket: 'testau-61f52.appspot.com',
    iosBundleId: 'com.example.flutterGoogle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfZIsE9b_idno3mscEFLM7KmpG50ocEV4',
    appId: '1:210878231216:web:7abc78338b1c9742664175',
    messagingSenderId: '210878231216',
    projectId: 'testau-61f52',
    authDomain: 'testau-61f52.firebaseapp.com',
    storageBucket: 'testau-61f52.appspot.com',
  );
}
